### ISSUE TITLE
Map rendering problem with OSM version

### ISSUE THREAD

**Issue by leoaltmann** [ge0rg/aprsdroid#117] opened 2015-12-31 05:50 UTC
Hello,
I am experiencing an issue with map rendering in the latest OSM build (2015-12-28).  Nothing other than the APRS symbols are plotted, and they are all located along the centerline.  That and areas of grey and white from zooming in and out.  Screenshots are attached below.  (Horizontal line across the screen is a hardware issue.)

I have tried two different .map files, the 2.5GB entire-USA one and another smaller one from Mapsforge and experienced the issue with both of them.

For comparison, I uninstalled the OSM version and installed the latest Google Maps version (aprsdroid-current).  That version runs without issue.

My hardware:  Dragon Touch M7 (generic cheap tablet) running Android 4.4.2.

73s,
KK6OCI

![img_1024](https://cloud.githubusercontent.com/assets/929068/12061585/1e19bf6a-af3f-11e5-9fd5-74ddbfc83bf3.jpg)
![img_1023](https://cloud.githubusercontent.com/assets/929068/12061586/24508396-af3f-11e5-9366-b453e023d69a.jpg)
![img_1025](https://cloud.githubusercontent.com/assets/929068/12061589/31674696-af3f-11e5-9951-3c0c9c26d0fb.jpg)

**Comment by leoaltmann** [comment] 2016-01-03 06:26
I was able to capture logcat output over USB while first loading the map, file attached for reference.  Thanks!

Steps:
- Close APRSdroid from app switcher
- Reset logcat
- Re-open APRSdroid
- Click map button
- Allow map to load; same visual effect observed
[logcat.txt](https://github.com/ge0rg/aprsdroid/files/76510/logcat.txt)


[logcat.txt](https://github.com/ge0rg/aprsdroid/files/76509/logcat.txt)

**Comment by jweisert** [comment] 2016-01-21 20:28
I have been experiencing a similar problem with the 2015-12-28 build. I had had this problem with earlier "straight" osm builds, but found that the maps are rendered correctly on my phone with the earlier "nojit" builds. Perhaps this might be the problem for leoaltmann as well.

Could someone please build a "nojit" version of the 2015-12-28 and place it in the build directory to see if this cures the rendering problem? Thanks.

My phone is a Maxwest Virture Z5 (chinese "generic" manufacturer) running Android 4.4.2

**Comment by ge0rg** [comment] 2016-09-09 17:16
Yeah, some exotic android devices fail to do hardware accelerated JIT, or somesuch. Please test this: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-09_osm_nojit.apk

**Comment by ge0rg** [comment] 2017-05-12 12:28
A new build: https://aprsdroid.org/download/builds/APRSdroid-gl-2017-05-12_osm_nojit.apk

While this is not a very nice workaround, the problem is only affecting a very small number of device, so I'm closing the issue for now.

**Closed by ge0rg** 2017-05-12 12:28 UTC
