### ISSUE TITLE
OSM Offline Map Loading Broken (Android 13 + others)

### ISSUE THREAD

**Issue by na7q** [ge0rg/aprsdroid#381] opened 2024-07-16 03:37 UTC
Did some digging and found that OSM offline maps has been broken after the Feb 26 2021 build. After this, it does not work. Tested on a couple different phones with similar results. Either not loading, or an error of the selected path.

**Comment by penguin359** [comment] 2024-07-17 05:10
I think this might be a duplicate of #328 which doesn't have an easy resolution for it. If you are using the Play Store version of Android, it requires targeting newer Android versions which breaks compatibility with the older MapForge library that is used. Please see this page for more details: https://github.com/ge0rg/aprsdroid/wiki/Offline-Maps

**Comment by na7q** [comment] 2024-07-17 05:25
I think that is the case. So then it appears broken for any newer OS. Very unfortunate. I think that is way beyond my understanding. I'm working on some minor changes and added features to a VARA HF build. Having maps would be a key thing for our users. 

Hopefully this is not a dead end.

**Closed** 2024-07-19 04:27 UTC
